# Generated by Django 3.2.20 on 2023-07-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_content',
            new_name='description',
        ),
    ]
