# Generated by Django 3.2.20 on 2023-07-08 09:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_report_content_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image_file',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
